### PR TITLE
[DF]❗High Priority Fixes

### LINKED ISSUE #201: [df] ambassadors, council & notifications [important]
### Hugo

- [x] * **Requests are not sorted (should be sorted by updatedAt because the value changes when an ambassador accepts or anything is edited)**

### Bernardo

- [x] * **As ambassador, I see the “report suspicious option” on the sidebar, but shouldn’t. **
- [x] “360” should be 60. Needs to be properly parsed**
- [x] * Community card is breaking -> `Previous PR`
- [x] * Report suspicious activity not opening for beneficiaries -> `Previous PR`

### PR DESCRIPTION
**Pull request by hugomarquesdev**
#201

### CODE REVIEW

**Comment by obernardovieira** [comment]
* Communities on homepage are sorted the wrong way
* Community card is breaking here. Is it fixed somewhere else?

Everything else looks good.

**Comment by hugomarquesdev** [comment]
> * Communities on homepage are sorted the wrong way
> * Community card is breaking here. Is it fixed somewhere else?
> 
> Everything else looks good 👏

@obernardovieira, fixed it.

**Review by obernardovieira — CHANGES_REQUESTED** [review]
I see you are sorting communities by `orderBy=newest`. Should be `orderBy=bigger`. That's what I meant before. Sorry if i was not clear.
Looks good then.

**Comment by hugomarquesdev** [comment]
> orderBy=bigger:DESC

@obernardovieira do you want the specific order to the community requests too?

**Comment by obernardovieira** [comment]
Both "community requests" for ambassadors and and "requests" on proposals page for council should be `orderBy=updated:DESC` (I don't think this order is available on API yet, ask João). This will always show first the ones that are receiving changes but also mixes together the newest because updated date by default is the creation date. There will have more ordering options later but for now this is good.

**Review by obernardovieira — APPROVED** [review]

**Review by PauloSousapt — APPROVED** [review]

**Pull request merged**
