### PR TITLE
Microcredit Manager: Repayments

### LINKED ISSUE #445: [mc manager] repayments tab (no actions)
Dependent on https://github.com/impactMarket/backend/issues/567

The first version of this repayments tab should only list the borrowers. No actions, selection boxes or anything. Just a list with profiles and when they've applied. I should open the borrower detail page, no activity as well, only an empty page with the option to change the wallet address

image

### PR DESCRIPTION
**Pull request by hugomarquesdev**
This PR fixes #445 

## Changes

- https://app-git-feature-microcredit-repayments-ipct.vercel.app/microcredit-manager

## Tests

- [ ] Tested on mobile
- [x] Tested on dektop

This PR should be manually tested by @obernardovieira @PauloSousapt , included on reviewers.

### CODE REVIEW

**Comment by obernardovieira** [comment]
Is it ready to review?

I have a weird scroll
and I guess you need to "* 1000" the last repayment date

https://github.com/impactMarket/app/assets/19441097/84b923aa-f370-4b92-9d22-8b8e04fba575

**Comment by hugomarquesdev** [comment]
> Is it ready to review?
> 
> I have a weird scroll and I guess you need to "* 1000" the last repayment date
> 
>  Gravacao.do.ecra.2023-05-09.as.17.31.44.mov

@obernardovieira fixed 👌

**Comment by obernardovieira** [comment]
looks nice. I see some "53 years ago". I guess it means no repayment

**Comment by hugomarquesdev** [comment]
> looks nice. I see some "53 years ago". I guess it means no repayment

@obernardovieira i was checking that right now. On the "53 years old" the `lastRepayment` field comes `null`.
should I hide it?

**Review by PauloSousapt — APPROVED** [review]

**Pull request merged**
