### PR TITLE
Remove Community button for Council Members

### LINKED ISSUE #337: add remove community button on community page, available to council members

### PR DESCRIPTION
**Pull request by hugomarquesdev**
This PR fixes #337 

## Changes

- _Remove Community_ button for Council Members.

## Tests

- [x] Tested on mobile
- [x] Tested on dektop

This PR should be manually tested by @obernardovieira @PauloSousapt , included on reviewers.

### CODE REVIEW

**Comment by Marianavpt** [comment]
If you need me to test this PR please let me know

**Comment by Marianavpt** [comment]
@hugomarquesdev , Reported by Catarina March 21st: 

When i try to edit the parameters of a community i got an error message. Anyway, the proposal is created and i get vote so i believe the only error is the message red instead of green, i am getting this error:


error

**Comment by hugomarquesdev** [comment]
> @hugomarquesdev , Reported by Catarina March 21st:
> 
> When i try to edit the parameters of a community i got an error message. Anyway, the proposal is created and i get vote so i believe the only error is the message red instead of green, i am getting this error:
> 
> error

@Marianavpt this PR is still in Draft, which means is not finished yet. no need to test it 😅

**Review by PauloSousapt — APPROVED** [review]

**Comment by Marianavpt** [comment]
Can we close this issue, @hugomarquesdev ?

**Comment by obernardovieira** [comment]
> Can we close this issue, @hugomarquesdev ?

It's closed. It'd be good to test during the next DF session.

**Pull request merged**
