### PR TITLE
Sidebar: Language Dropdown for Logged Out Users

### LINKED ISSUE #329: not changing language when user is not logged in

### PR DESCRIPTION
**Pull request by hugomarquesdev**
This PR fixes #329 

## Changes

- 

## Tests

- [x] Tested on mobile
- [x] Tested on dektop

This PR should be manually tested by @obernardovieira @PauloSousapt , included on reviewers.

### CODE REVIEW

**Comment by obernardovieira** [comment]
Given that my browser is in Portuguese, can we make it default to Portuguese already?
Looks really nice 👏

**Comment by hugomarquesdev** [comment]
@obernardovieira there's kinda a problem with portuguese language... because the webapp doesn't have `pt_PT` but `pt_BR`...
i can do that with a workaround that if it's `pt_PT` automatically translates to `pt_BR`

**Comment by obernardovieira** [comment]
That will happen for any language because we don't have all those locales.
As an example, what we do on the wallet is use just the first part, like pt_PT or pt_BR, would be just pt. Same as fr_FR or fr_LU would be just fr. IDK how to use that on web though

**Review by PauloSousapt — APPROVED** [review]

**Comment by hugomarquesdev** [comment]
> That will happen for any language because we don't have all those locales. As an example, what we do on the wallet is use just the first part, like pt_PT or pt_BR, would be just pt. Same as fr_FR or fr_LU would be just fr. IDK how to use that on web though

@obernardovieira 
fixed it.
basically: the first time you open the webapp it saves a cookie with the browser language and set it as default language. 
in case you want to change language, you can change manually on the select dropdown and it changes that cookie, which means if you access the website again it saved the new language you chose.

**Review by obernardovieira — APPROVED** [review]

**Pull request merged**
