### PR TITLE
Github issues and LaE updates

### PR DESCRIPTION
**Pull request by PauloSousapt**
This PR fixes  
- #407
- #406
- #405
- #404
- #397
- Fixes shortcuts page not updating locale when prismic data changes

## Changes
- Add logic to LaE tabs to make started as default if exists and hide the ones that don't have results

## Tests

- [x] Tested on mobile
- [x] Tested on dektop

This PR should be manually tested by @obernardovieira @hugomarquesdev , included on reviewers.

### CODE REVIEW

**Comment by obernardovieira** [comment]
* After opening a beneficiary detail, if I go back with browser options, rather than back in-app, I see a 404 page. Is it happening just to me?
* I have a 404 in /communities page

**Comment by obernardovieira** [comment]
Hopefully this helps

https://user-images.githubusercontent.com/19441097/224026098-2fcd2d55-eb4d-4150-808d-5043e6330c92.mov

**Comment by PauloSousapt** [comment]
Still unable to reproduce that issue, on my side everything is working, although i added some changes to enforce the state and page when they aren't present, its my guess of what can be causing the problem. When you have the chance please test again.

https://user-images.githubusercontent.com/20448010/224167041-0b4b59dd-6c18-4cba-8255-edebc9d73bdf.mov

**Review by obernardovieira — APPROVED** [review]

**Comment by obernardovieira** [comment]
> https://docs.google.com/presentation/d/1tix5M9CysQIpwm8wJ83Hs2hpGxi2GbLGnIr1tNNFS5A/edit#slide=id.g21507b96cfd_0_27 @obernardovieira

No need to tag, but if you want, tag the author.
@PauloSousapt in this case.

**Comment by obernardovieira** [comment]
I'll merge this to move forward. No bigger issues pointed.

**Pull request merged**
